// Generated by CoffeeScript 1.7.1
(function() {
  var advanceBody;

  advanceBody = null;

  self.addEventListener('message', function(e) {
    var command, time;
    switch (e.data.type) {
      case 'initialize':
        console.log("worker received initialize: " + JSON.stringify(e.data, null, 2));
        eval(e.data.code);
        advanceBody = advance;
        return self.postMessage({
          type: 'initialized'
        });
      case 'advance':
        console.log("worker received advance: " + JSON.stringify(e.data, null, 2));
        time = new Date().getTime();
        command = advanceBody(e.data.context);
        time = new Date().getTime() - time;
        return self.postMessage({
          type: 'advanced',
          command: command,
          time: time
        });
    }
  }, false);

}).call(this);
